const { createDefaultProviderRegistry } = require("../providers");

const INTERNALS = {
  SUPPORTED_CRITERIA: [
    "player",
    "year",
    "set",
    "cardNumber",
    "number",
    "brand",
    "season",
    "parallel",
    "variation",
    "grade",
  ],
  SEARCH_PRIORITY: [
    "player",
    "year",
    "set",
    "cardNumber",
    "brand",
    "season",
    "parallel",
    "variation",
    "grade",
  ],
  SCORE_WEIGHTS: {
    player: 35,
    year: 20,
    set: 20,
    cardNumber: 14,
    brand: 5,
    season: 3,
    parallel: 2,
    variation: 1,
  },
};

function assertPlainObject(value, message) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(message);
  }
}

function toNullableNormalizedString(value) {
  if (value === undefined || value === null) {
    return null;
  }

  const normalized = String(value).trim();

  if (normalized === "") {
    return null;
  }

  return normalized;
}

function toNullableNormalizedInteger(value) {
  if (value === undefined || value === null) {
    return null;
  }

  if (typeof value === "number" && Number.isFinite(value)) {
    return Math.trunc(value);
  }

  if (typeof value === "string") {
    const normalized = value.trim();

    if (normalized === "") {
      return null;
    }

    const asInteger = Number.parseInt(normalized, 10);

    if (!Number.isNaN(asInteger)) {
      return asInteger;
    }
  }

  return null;
}

function normalizeCriteria(input) {
  assertPlainObject(input, "Les criteres de card matching sont invalides.");

  const normalized = {
    provider: toNullableNormalizedString(input.provider),
  };

  for (const key of INTERNALS.SUPPORTED_CRITERIA) {
    if (key === "year") {
      normalized.year = toNullableNormalizedInteger(input.year);
      continue;
    }

    if (key === "number") {
      continue;
    }

    normalized[key] = toNullableNormalizedString(input[key]);
  }

  // Compatibility alias: number -> cardNumber
  if (!normalized.cardNumber) {
    normalized.cardNumber = toNullableNormalizedString(input.number);
  }

  return normalized;
}

function buildSearchStrategy(criteria) {
  const strategy = [];

  for (let keepCount = INTERNALS.SEARCH_PRIORITY.length; keepCount >= 1; keepCount -= 1) {
    const activeKeys = INTERNALS.SEARCH_PRIORITY.slice(0, keepCount);
    const candidate = {};

    for (const key of activeKeys) {
      if (criteria[key] !== null) {
        candidate[key] = criteria[key];
      }
    }

    if (Object.keys(candidate).length > 0) {
      strategy.push(candidate);
    }
  }

  // Remove duplicate strategy steps generated by missing optional fields.
  const unique = [];
  const fingerprints = new Set();

  for (const step of strategy) {
    const fingerprint = JSON.stringify(step);

    if (fingerprints.has(fingerprint)) {
      continue;
    }

    fingerprints.add(fingerprint);
    unique.push(step);
  }

  if (unique.length === 0) {
    throw new Error("Au moins un critere de card matching est requis.");
  }

  return unique;
}

function normalizeForComparison(value) {
  if (value === undefined || value === null) {
    return "";
  }

  return String(value).trim().toLowerCase();
}

function scoreField(expectedValue, candidateValue, maxWeight) {
  if (expectedValue === null || expectedValue === undefined) {
    return 0;
  }

  const expected = normalizeForComparison(expectedValue);
  const actual = normalizeForComparison(candidateValue);

  if (expected === "" || actual === "") {
    return 0;
  }

  if (expected === actual) {
    return maxWeight;
  }

  if (actual.includes(expected) || expected.includes(actual)) {
    return Math.round(maxWeight * 0.5);
  }

  return 0;
}

function scoreCandidate(criteria, candidate) {
  let total = 0;
  const details = {};

  for (const [field, weight] of Object.entries(INTERNALS.SCORE_WEIGHTS)) {
    const score = scoreField(criteria[field], candidate[field], weight);
    details[field] = score;
    total += score;
  }

  return {
    score: total,
    details,
  };
}

function toConfidence(score, maxScore) {
  if (maxScore <= 0) {
    return 0;
  }

  const percentage = Math.round((score / maxScore) * 100);

  return Math.max(0, Math.min(100, percentage));
}

function createResult(step, scoredCandidates, maxScore) {
  const sorted = [...scoredCandidates].sort((a, b) => b.score - a.score);
  const best = sorted[0] || null;

  return {
    strategyStep: step,
    totalCandidates: sorted.length,
    bestMatch: best
      ? {
          score: best.score,
          confidence: toConfidence(best.score, maxScore),
          scoring: best.scoring,
          card: best.card,
        }
      : null,
    candidates: sorted.map((entry) => ({
      score: entry.score,
      confidence: toConfidence(entry.score, maxScore),
      scoring: entry.scoring,
      card: entry.card,
    })),
  };
}

function assertProviderResponse(response) {
  if (!response || typeof response !== "object" || Array.isArray(response)) {
    throw new Error("La reponse provider de card matching est invalide.");
  }

  if (!Array.isArray(response.candidates)) {
    throw new Error("La reponse provider de card matching doit contenir un tableau candidates.");
  }
}

function createCardMatchingEngine(options = {}) {
  const registry = options.providerRegistry || createDefaultProviderRegistry();

  assertPlainObject(registry, "Le registry de providers de card matching est invalide.");

  if (typeof registry.resolve !== "function") {
    throw new Error("Le registry de card matching doit exposer resolve(providerId).");
  }

  const maxScore = Object.values(INTERNALS.SCORE_WEIGHTS).reduce((sum, value) => sum + value, 0);

  async function matchCard(criteriaInput) {
    const criteria = normalizeCriteria(criteriaInput);
    const provider = registry.resolve(criteria.provider);
    const strategy = buildSearchStrategy(criteria);

    for (const step of strategy) {
      const response = await provider.searchCards(step);
      assertProviderResponse(response);

      if (response.candidates.length === 0) {
        continue;
      }

      const scoredCandidates = response.candidates.map((card) => {
        const scoring = scoreCandidate(criteria, card);

        return {
          card,
          score: scoring.score,
          scoring: scoring.details,
        };
      });

      const result = createResult(step, scoredCandidates, maxScore);

      return {
        provider: provider.id,
        requestedCriteria: criteria,
        strategyLength: strategy.length,
        status: result.bestMatch ? "MATCH_FOUND" : "NO_MATCH",
        ...result,
      };
    }

    return {
      provider: provider.id,
      requestedCriteria: criteria,
      strategyLength: strategy.length,
      status: "NO_MATCH",
      strategyStep: strategy[strategy.length - 1] || null,
      totalCandidates: 0,
      bestMatch: null,
      candidates: [],
    };
  }

  return Object.freeze({
    matchCard,
    buildSearchStrategy,
  });
}

module.exports = {
  createCardMatchingEngine,
};
